---
- name: PLAY 01 --- TEST CONNECTIVITY TO GNS3 LAB
  hosts: routers
  connection: network_cli
  gather_facts: no

  tasks:
    - name: PLAY 01 --- RUN "sh ip int br" CMD
      ios_command:
        commands: sh ip int br
      register: results

    - name: PLAY 02 --- DISPLAY RESULTS
      debug:
        var: results